"""Transparent classification, anomaly, behavioral evidence, and risk policy."""

from __future__ import annotations

import math
from typing import Any

from .models import CLASS_SEVERITY, anomaly_score, classify


DEFAULT_RISK_WEIGHTS = {"anomaly": 0.30, "classifier": 0.45, "behavior": 0.25}
DEFAULT_HEURISTIC_THRESHOLDS = {
    "unique_ports": 5,
    "unique_destinations": 10,
    "connections_30s": 15,
    "short_lived_connections": 12,
    "failed_auth": 5,
    "failure_ratio": 0.7,
    "unique_accounts": 4,
    "new_internal_peers": 3,
    "admin_service_access": 5,
    "outbound_bytes": 1_000_000,
    "minimum_transfer_bytes": 500_000,
    "outbound_inbound_ratio": 8.0,
    "outbound_baseline_multiplier": 8.0,
    "denied_events": 5,
}


def _feature_evidence(
    event: dict[str, Any],
    feature: str,
    value: float,
    threshold: float,
    explanation: str,
    strength: float,
) -> dict[str, Any]:
    return {
        "type": feature,
        "feature": feature,
        "value": value,
        "threshold": threshold,
        "contribution": 0.0,
        "explanation": explanation,
        "observation": explanation,
        "record_id": event["record_id"],
        "timestamp": event["timestamp"],
        "source_ip": event["source_ip"],
        "destination_ip": event["destination_ip"],
        "_strength": min(1.0, max(0.0, strength)),
    }


def _behavior_evidence(
    event: dict[str, Any], features: dict[str, Any], thresholds: dict[str, float]
) -> list[dict[str, Any]]:
    evidence: list[dict[str, Any]] = []
    ports = features["window_unique_ports"]
    destinations = features["window_unique_destinations"]
    rate_count = features["window_short_event_count"]
    failures = features["window_failed_auth"]
    failure_ratio = features["window_failure_ratio"]
    auth_accounts = features["window_unique_accounts"]
    new_internal = features["window_new_internal_peers_60s"]
    admin_access = features["window_admin_service_access_60s"]
    outbound_bytes = features["window_bytes_sent"]
    outbound_ratio = features["window_outbound_inbound_ratio"]
    outbound_multiplier = features["window_bytes_vs_prior_average"]
    denied = features["window_denied"]
    short_lived = features["window_short_lived_connections"]

    def add(feature: str, value: float, threshold: float, message: str, strength: float | None = None) -> None:
        evidence.append(_feature_evidence(
            event, feature, value, threshold, message,
            strength if strength is not None else value / max(threshold, 1),
        ))

    if ports >= thresholds["unique_ports"]:
        add("window_unique_ports", ports, thresholds["unique_ports"],
            f"{int(ports)} unique destination ports contacted in the rolling window")
    if destinations >= thresholds["unique_destinations"]:
        add("window_unique_destinations", destinations, thresholds["unique_destinations"],
            f"{int(destinations)} distinct destinations contacted in the rolling window")
    if rate_count >= thresholds["connections_30s"]:
        add("window_short_event_count", rate_count, thresholds["connections_30s"],
            f"{int(rate_count)} connections generated by source within 30 seconds")
    if short_lived >= thresholds["short_lived_connections"]:
        add("window_short_lived_connections", short_lived, thresholds["short_lived_connections"],
            f"{int(short_lived)} short-lived connections observed in 60 seconds")
    if failures >= thresholds["failed_auth"]:
        add("window_failed_auth", failures, thresholds["failed_auth"],
            f"{int(failures)} failed authentication events observed in the rolling window")
    if failures >= 3 and failure_ratio >= thresholds["failure_ratio"]:
        add("window_failure_ratio", failure_ratio, thresholds["failure_ratio"],
            f"authentication failure ratio is {failure_ratio:.1%} ({int(failures)} failures)")
    if auth_accounts >= thresholds["unique_accounts"]:
        add("window_unique_accounts", auth_accounts, thresholds["unique_accounts"],
            f"authentication attempts span {int(auth_accounts)} distinct accounts")
    if new_internal >= thresholds["new_internal_peers"]:
        explanation = (
            f"source contacted {int(new_internal)} previously unseen internal peers within 60 seconds"
        )
        if admin_access:
            explanation += f", including {int(admin_access)} administrative-service connections"
        add("window_new_internal_peers_60s", new_internal, thresholds["new_internal_peers"], explanation)
    if admin_access >= thresholds["admin_service_access"]:
        add("window_admin_service_access_60s", admin_access, thresholds["admin_service_access"],
            f"{int(admin_access)} connections to administrative/service ports in 60 seconds")
    if outbound_bytes >= thresholds["outbound_bytes"]:
        add("window_bytes_sent", outbound_bytes, thresholds["outbound_bytes"],
            f"{outbound_bytes / 1_000_000:.2f} MB outbound in the rolling window")
    if outbound_bytes >= thresholds["minimum_transfer_bytes"] and outbound_ratio >= thresholds["outbound_inbound_ratio"]:
        add("window_outbound_inbound_ratio", outbound_ratio, thresholds["outbound_inbound_ratio"],
            f"outbound/inbound byte ratio is {outbound_ratio:.1f}×")
    if outbound_bytes >= thresholds["minimum_transfer_bytes"] and outbound_multiplier >= thresholds["outbound_baseline_multiplier"]:
        add("window_bytes_vs_prior_average", outbound_multiplier, thresholds["outbound_baseline_multiplier"],
            f"outbound volume increased {outbound_multiplier:.1f}× relative to this source's prior event average")
    if denied >= thresholds["denied_events"]:
        add("window_denied", denied, thresholds["denied_events"],
            f"{int(denied)} denied or blocked events in the rolling window")
    return evidence


def assess(
    event: dict[str, Any],
    features: dict[str, Any],
    model: dict[str, Any],
    *,
    weights: dict[str, float] | None = None,
    thresholds: dict[str, float] | None = None,
) -> dict[str, Any]:
    weights = dict(DEFAULT_RISK_WEIGHTS if weights is None else weights)
    if set(weights) != {"anomaly", "classifier", "behavior"}:
        raise ValueError("Risk weights must define anomaly, classifier, and behavior.")
    if any(value < 0 for value in weights.values()) or sum(weights.values()) <= 0:
        raise ValueError("Risk weights must be non-negative and have a positive total.")
    weight_total = sum(weights.values())
    weights = {name: value / weight_total for name, value in weights.items()}
    configured_thresholds = dict(DEFAULT_HEURISTIC_THRESHOLDS)
    if thresholds:
        unknown = set(thresholds) - set(configured_thresholds)
        if unknown:
            raise ValueError(f"Unknown heuristic thresholds: {', '.join(sorted(unknown))}.")
        if any(
            not isinstance(value, (int, float)) or not math.isfinite(value) or value < 0
            for value in thresholds.values()
        ):
            raise ValueError("Heuristic thresholds must be finite non-negative numbers.")
        configured_thresholds.update(thresholds)
    thresholds = configured_thresholds
    probabilities = classify(model, features)
    predicted_class = max(probabilities, key=probabilities.get)
    confidence = probabilities[predicted_class]
    threat_confidence = max(
        (probability * CLASS_SEVERITY.get(label, 0.0) for label, probability in probabilities.items()),
        default=0.0,
    )
    anomaly = anomaly_score(model, features)
    anomaly_threshold = float(model.get("anomaly_detector", {}).get("threshold", 0.6))
    behavior_evidence = _behavior_evidence(event, features, thresholds)
    behavior_strength = max((item["_strength"] for item in behavior_evidence), default=0.0)

    components = {
        "anomaly": 100 * weights["anomaly"] * anomaly,
        "classifier": 100 * weights["classifier"] * threat_confidence,
        "behavioral_evidence": 100 * weights["behavior"] * behavior_strength,
    }
    noise_discount = 0.65 if event.get("is_noise") and not behavior_evidence else 1.0
    if noise_discount != 1.0:
        components = {name: value * noise_discount for name, value in components.items()}
    risk = min(100, max(0, round(sum(components.values()))))
    band = "Malicious" if risk >= 71 else "Suspicious" if risk >= 31 else "Normal"

    behavior_strength_total = max(
        sum(item["_strength"] for item in behavior_evidence), 1e-12
    )
    for item in behavior_evidence:
        item["contribution"] = round(
            components["behavioral_evidence"] * item["_strength"] /
            behavior_strength_total,
            2,
        )
        item.pop("_strength")
    evidence = list(behavior_evidence)
    if event.get("is_noise"):
        reasons = event.get("noise_reasons", [])
        evidence.append({
            "type": "background_noise",
            "feature": "is_noise",
            "value": True,
            "threshold": None,
            "contribution": 0.0,
            "explanation": (
                "Background/noise indicator: " + "; ".join(reasons)
                if reasons else "Record matched a configured background/noise indicator"
            ),
            "observation": "background traffic was tagged and de-prioritized",
            "record_id": event["record_id"],
            "timestamp": event["timestamp"],
            "source_ip": event["source_ip"],
            "destination_ip": event["destination_ip"],
        })
    evidence.append({
        "type": "unsupervised_anomaly",
        "feature": "anomaly_score",
        "value": anomaly,
        "threshold": model.get("anomaly_detector", {}).get("threshold", 0.6),
        "contribution": round(components["anomaly"], 2),
        "explanation": (
            f"{model.get('anomaly_detector', {}).get('name', 'robust-mad')} normalized anomaly score "
            f"{anomaly:.3f}; decision "
            f"{'anomalous' if anomaly >= anomaly_threshold else 'within baseline'}"
        ),
        "observation": f"unsupervised anomaly score {anomaly:.3f} (0..1)",
        "record_id": event["record_id"],
        "timestamp": event["timestamp"],
        "source_ip": event["source_ip"],
        "destination_ip": event["destination_ip"],
    })
    if anomaly > 0:
        baseline = model.get("robust_baseline", {})
        detector_features = model.get("anomaly_detector", {}).get("features", list(baseline))
        for feature in detector_features:
            if feature not in baseline or feature not in features:
                continue
            median, scale = baseline[feature]
            value = float(features[feature])
            deviation = abs(value - median) / max(float(scale), 1e-9)
            if deviation >= 3:
                anomaly_feature = _feature_evidence(
                    event, feature, value, float(median),
                    f"{feature}={value:g} deviates {deviation:.1f} robust scales from Normal baseline {median:g}",
                    deviation / 12,
                )
                anomaly_feature.pop("_strength")
                evidence.append(anomaly_feature)
    evidence.append({
        "type": "model_classification",
        "feature": "predicted_class",
        "value": predicted_class,
        "threshold": None,
        "contribution": round(components["classifier"], 2),
        "explanation": f"model estimates {predicted_class} with {confidence:.1%} confidence",
        "observation": f"predicted {predicted_class} with {confidence:.1%} confidence",
        "record_id": event["record_id"],
        "timestamp": event["timestamp"],
        "source_ip": event["source_ip"],
        "destination_ip": event["destination_ip"],
    })
    if not evidence:
        evidence.append({
            "type": "observed_baseline",
            "feature": "baseline",
            "value": 0,
            "threshold": None,
            "contribution": 0.0,
            "explanation": "no configured behavioral threshold was crossed",
            "observation": "no configured behavioral threshold was crossed",
            "record_id": event["record_id"],
            "timestamp": event["timestamp"],
            "source_ip": event["source_ip"],
            "destination_ip": event["destination_ip"],
        })
    contributing_record_ids = list(features.get("window_record_ids", [event["record_id"]]))
    for item in evidence:
        item["raw_record_ids"] = contributing_record_ids
    evidence.sort(key=lambda item: item["contribution"], reverse=True)
    return {
        "event": event,
        "features": features,
        "risk": risk,
        "band": band,
        "predicted_class": predicted_class,
        "confidence": confidence,
        "anomaly_score": anomaly,
        "anomaly_decision": "anomalous" if anomaly >= anomaly_threshold else "within_baseline",
        "detector": model.get("anomaly_detector", {}).get("name", "robust-mad"),
        "risk_components": components,
        "noise_discount": noise_discount,
        "raw_event_ids": contributing_record_ids,
        "risk_weights": weights,
        "evidence": evidence,
        "model_probabilities": probabilities,
        "model_version": str(model.get("format_version", "unknown")),
    }


def render_text(result: dict[str, Any]) -> str:
    event = result["event"]
    lines = [
        f"[{result['band'].upper():10}] risk={result['risk']:3}/100 "
        f"class={result['predicted_class']} confidence={result['confidence']:.1%}",
        f"  record={event['record_id']} line={event['line_number']} "
        f"{event['timestamp']} {event['source_ip']} -> {event['destination_ip']} "
        f"type={event['event_type']}",
        f"  components={result['risk_components']} detector={result['detector']} "
        f"anomaly={result['anomaly_score']:.3f} ({result['anomaly_decision']})",
    ]
    lines.extend(f"  evidence: {item['explanation']}" for item in result["evidence"])
    return "\n".join(lines)
